### ISSUE TITLE
New Dati

### ISSUE THREAD

**Issue by Giasinit** [peterampazzo/OpenData-Padova#1]
Ciao @peterampazzo, grazie della tua repository!

Dopo 8 anni dall'ultimo commit, voglio contribuire a migliorare il tuo progetto.
Grazie alle API di MyCicero/MooneyGo sono riuscito a recuperare TUTTE LE FERMATE di Busitalia Veneto/APS Mobilita sia Urbane che Extraurbane.

Il file è in JSON, però non ne conosco la licenza.
Visto che ho solo fatto una richiesta al server di MyCicero che mi ha restituito le fermate salvate con altrettanto di coordinate, codice fermata, nome della fermata e se è urbano o extraurbano.

Dimmi te come possiamo fare.
Grazie e buonaserata :)

**Comment by peterampazzo** [comment]
Ciao! Se hai voglia apri pure una PR aggiornando la tabella, specificando il link e il fonte :)

**Comment by Giasinit** [comment]
Fatto! Grazie del tuo tempo.
